module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fffffe',
        headline: '#272343',
        paragraph: '#2d334a',
        button: '#ffd803',
        'button-text': '#272343',
        stroke: '#272343',
        main: '#fffffe',
        highlight: '#ffd803',
        secondary: '#e3f6f5',
        tertiary: '#bae8e8',

        text: '#37352f',

        'tag-default': '#e9e8e7',
        'tag-gray': '#e3e2e0',
        'tag-brown': '#eee0da',
        'tag-red': '#ffe2dd',
        'tag-orange': '#fadec9',
        'tag-yellow': '#fdecc8',
        'tag-green': '#dbeddb',
        'tag-blue': '#d3e5ef',
        'tag-purple': '#e8deee',
        'tag-pink': '#f5e0e9',
        'tag-text-default': '#32302c',
        'tag-text-gray': '#32302c',
        'tag-text-brown': '#442a1e',
        'tag-text-red': '#5d1715',
        'tag-text-orange': '#49290e',
        'tag-text-yellow': '#402c1b',
        'tag-text-green': '#1c3829',
        'tag-text-blue': '#183347',
        'tag-text-purple': '#412454',
        'tag-text-pink': '#4c2337',

        'rich-default': '#37352f',
        'rich-code': '#eb5757',
        'rich-code_background': '#ededeb',
        'rich-gray': '#787774',
        'rich-brown': '#9f6b53',
        'rich-orange': '#d9730d',
        'rich-yellow': '#cb912f',
        'rich-green': '#448361',
        'rich-blue': '#337ea9',
        'rich-purple': '#9065b0',
        'rich-pink': '#c14c8a',
        'rich-red': '#d44c47',
        'rich-gray_background': '#f1f1ef',
        'rich-brown_background': '#f4eeee',
        'rich-orange_background': '#fbecdd',
        'rich-yellow_background': '#fbf3db',
        'rich-green_background': '#edf3ec',
        'rich-blue_background': '#e7f3f8',
        'rich-purple_background': '#f6f3f9',
        'rich-pink_background': '#faf1f5',
        'rich-red_background': '#fdebec',
      },
    },
  },
  plugins: [],
};
