module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fffffe',
        headline: '#272343',
        paragraph: '#2d334a',
        button: '#ffd803',
        'button-text': '#272343',
        stroke: '#272343',
        main: '#fffffe',
        highlight: '#ffd803',
        secondary: '#e3f6f5',
        tertiary: '#bae8e8',

        text: '#37352f',
        // tag bg colors
        'tag-default': '#e9e8e7',
        'tag-gray': '#e3e2e0',
        'tag-brown': '#eee0da',
        'tag-red': '#ffe2dd',
        'tag-orange': '#fadec9',
        'tag-yellow': '#fdecc8',
        'tag-green': '#dbeddb',
        'tag-blue': '#d3e5ef',
        'tag-purple': '#e8deee',
        'tag-pink': '#f5e0e9',
        // tag bg dark colors
        'tag-default-dark': '#474747',
        'tag-gray-dark': '#5a5a5a',
        'tag-brown-dark': '#603b2c',
        'tag-red-dark': '#6e3630',
        'tag-orange-dark': '#854c1d',
        'tag-yellow-dark': '#89632a',
        'tag-green-dark': '#2b593f',
        'tag-blue-dark': '#28456c',
        'tag-purple-dark': '#492f64',
        'tag-pink-dark': '#69314c',
        // tag text colors
        'tag-text-default': '#32302c',
        'tag-text-gray': '#32302c',
        'tag-text-brown': '#442a1e',
        'tag-text-red': '#5d1715',
        'tag-text-orange': '#49290e',
        'tag-text-yellow': '#402c1b',
        'tag-text-green': '#1c3829',
        'tag-text-blue': '#183347',
        'tag-text-purple': '#412454',
        'tag-text-pink': '#4c2337',
        // tag text dark color
        'tag-text-dark': '#d8d8d8',

        // rich text colors
        'rich-default': '#37352f',
        'rich-code': '#eb5757',
        'rich-underline': '#babab7',
        'rich-gray': '#787774',
        'rich-brown': '#9f6b53',
        'rich-orange': '#d9730d',
        'rich-yellow': '#cb912f',
        'rich-green': '#448361',
        'rich-blue': '#337ea9',
        'rich-purple': '#9065b0',
        'rich-pink': '#c14c8a',
        'rich-red': '#d44c47',
        // rich text dark colors
        'rich-default-dark': '#e2e2e2',
        'rich-code-dark': '#b24b4a',
        'rich-underline-dark': '#e5e5e5',
        'rich-gray-dark': '#9b9b9b',
        'rich-brown-dark': '#ba856f',
        'rich-orange-dark': '#c77d48',
        'rich-yellow-dark': '#ca9849',
        'rich-green-dark': '#529e72',
        'rich-blue-dark': '#5e87c9',
        'rich-purple-dark': '#9d68d3',
        'rich-pink-dark': '#d15796',
        'rich-red-dark': '#df5452',

        // rich text bg colors
        'rich-code_background': '#ededeb',
        'rich-gray_background': '#f1f1ef',
        'rich-brown_background': '#f4eeee',
        'rich-orange_background': '#fbecdd',
        'rich-yellow_background': '#fbf3db',
        'rich-green_background': '#edf3ec',
        'rich-blue_background': '#e7f3f8',
        'rich-purple_background': '#f6f3f9',
        'rich-pink_background': '#faf1f5',
        'rich-red_background': '#fdebec',
        // rich text bg dark colors
        'rich-code_background-dark': '#2f2f2d',
        'rich-gray_background-dark': '#2f2f2f',
        'rich-brown_background-dark': '#4a3228',
        'rich-orange_background-dark': '#5c3b23',
        'rich-yellow_background-dark': '#564328',
        'rich-green_background-dark': '#243d30',
        'rich-blue_background-dark': '#143a4e',
        'rich-purple_background-dark': '#4e2c3c',
        'rich-pink_background-dark': '#4e2c3c',
        'rich-red_background-dark': '#522e2a',
      },
    },
  },
  plugins: [],
};
